'''
OOP IS IS A PROGRAMMING PARADIGM THAT USES OBJECTS AND CLASSES IN PROGRAMMING.
OOPS, CONCEPTS IN PYTHON, AIM TO IMPLEMENT REAL-WORLD ENTITIES LIKE INHERITANCE, POLYMORPHISMS, ENCAPSULATION
'''
'''
WHAT IS CLASS IN PYTHON: A CODE TEMPLATE FOR CREATING OBJECTS. OBJECTS HAVE MEMBER VARIABLES AND HAVE BEHAVIOUR ASSOCIATED WITH THEM.
IN PYTHON A CLASS IS CREATED BY THE KEYWORD CLASS
'''
#HOW TO DEFINE NEW CLASS
class CarFactor:
    pass


'''
WHAT IS OBJECT: VARIBLES THAT CONTAIN DATA AND FUNCTIONS THAT CAN BE USED TO MANIPULATE THE DATA
'''
#HOE TO DEFINE NEW INSTANCE (OBJECT)
BMW = CarFactor()
print(BMW) #OUTPUT: <__main__.CarFactor object at 0x0000027B7B5198B0> 